"use client";
import type { Metadata } from "next";
import { Inter, Poppins, Roboto } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/header/header";
import Footer from "./components/layout/footer/footer";
import { NextUIProvider } from "@nextui-org/react";
import { usePathname } from "next/navigation";
import HeaderAdmin from "./components/admin/header/admin-header";
// import { useRouter } from "next/navigation";

// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
// });
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});
const metadata: Metadata = {
  title: "eduxLL",
  //description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const path = usePathname();

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={roboto.className}>
        {path === "/admin/dashboard" ||
        path === "/admin/courses" ||
        path === "/admin/blogs" ||
        path === "/admin/courses/create-course" ||
        path === "/admin/not-found" ||
        path === "/admin/blogs/create-blog" ? (
          <div className="flex gap-4 p-6">
            <HeaderAdmin />
            <div className="w-full bg-[#e5e5e5] h-screen">{children}</div>
          </div>
        ) : (
          <>
            <div>{children}</div>
          </>
        )}
      </body>
    </html>
  );
}
